version: '3.8'
services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts-jdk11
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /home/rterrero/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      #- /home/rterrero/nginx_letsencrypt/config/etc/letsencrypt/live/raykert.com:/swag-ssl
      -  /home/rterrero/nginx_letsencrypt/config/keys:/swag-ssl
volumes:
  jenkins-home:
